version: '3.8'

services:

  db:
    image: abidh/postgres
    hostname: db
    container_name: abidh-postgres
    # restart: always
    # use the below restore command if you need to restore onto a new database container. THen comment and docker-compose up or use docker run normally
    # command: pgbackrest restore --stanza=pgbackrest_test_stanza_name --delta --log-level-console=detail
    # command: pgbackrest restore --stanza=pgbackrest_BACKEDUP_stanza --repo1-path=/pgbackrest-test  --pg1-path=/var/lib/postgresql/data/ --delta --type=immediate --log-level-console=detail --recovery-option=recovery_target_action=promote
    environment:
      # - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Postgres
    ports:  
      - '5432:5432'
    # volumes: 
      # - ./_pgdata:/var/lib/postgresql/data
      # - db:/var/lib/postgresql/data
      # copy the sql script to startup scripts section to create tables on startup
      # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # to change the config file Postgres will use. You'd mount your custom config file with a volume:
      #  - ./customPostgresql.conf:/etc/postgresql.conf

# volumes:
#   db:
#     driver: local